### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by devmotion** [JuliaMath/IrrationalConstants.jl#10]
It seems that currently there are not many active maintainers of this repository as there are 4 open PRs that are ready for review and in a reasonably good shape but 3 of them haven't received any comment from any JuliaMath member at all (one was opened two weeks ago, the others one month and two months ago). This is quite unfortunate since IrrationalConstants is tightly integrated in the Julia ecosystem via e.g. SpecialFunctions and LogExpFunctions (and hence also StatsFuns). I would like to help with maintaining this package but I don't have any permissions for this repo (not a member of JuliaMath either) and I can't review my own PRs.

**Comment by devmotion** [comment]
I was added to the JuliaMath organization (thanks @giordano!) and merged some uncontroversial PRs (adding `inv(sqrt(pi))`, `log(10)` and improving `log(big(2))`). Nevertheless an additional active maintainer would be good, also to review my other PR and to discuss the PR for `inv`.

**Comment by waldyrious** [comment]
@devmotion, just so the information is explicit — have additional maintainers been added, or did you give up searching for more? (Or are still looking but prefer not to have the open issue lying around?)

**Comment by devmotion** [comment]
Activity in the repo had increased (for a while at least) and it didn't seem to be particularly helpful to keep the issue open.
