### ISSUE TITLE
Is explicit reset of precision helpful?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/IrrationalConstants.jl#27]
Currently, the definitions use the precision set for `BigFloat` / MPFR as it happens to be when the package is `using`ed.
Does it make sense to include e.g. `setprecision(BigFloat, max(precision(BigFloat), 256))` before the `include`s?

**Comment by devmotion** [comment]
I'm not sure I understand. IrrationalConstants should use exactly the same behaviour as Base when defining irrationals (just a separate type system to avoid type piracy which IMO should be adopted by Base), so in case there are issues with this behaviour I think they should be fixed upstream first.

**Comment by JeffreySarnoff** [comment]
That is (half of) the issue.  Base uses `setprecision(BigFloat, 256)`.
If I do this:
```
(somewhere else) setprecision(BigFloat, 128)
using IrrationalConstants
```
my irrational constants will be created with 128 BigFloats ..
so `BigFloat(<irrationalconstant>)` will have less precision than one gets with Base.

**Comment by devmotion** [comment]
The irrational constants are not defined as `BigFloat`s, so I don't know what exactly you refer to when you write "my irrational constants will be created with 128 BigFloats". Irrational constants can be converted to `BigFloat`s explicitly, in which case the precision by default will be set to `precision(BigFloat)` but can be specified explicitly as keyword argument `precision`.

**Comment by JeffreySarnoff** [comment]
ok --
