### ISSUE TITLE
Rename Irrationals.jl?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/IrrationalConstants.jl#4]
Just wanted to throw this out there before this gets registered: maybe Irrationals.jl is better since the Julia type ` Irrational ` implies it’s a constant anyways

**Comment by JeffreySarnoff** [comment]
ok by me

**Comment by devmotion** [comment]
The irrationals defined with the `@irrational` macro are constant in the mathematical sense but their arbitrary-precision values are not constant but depend on the desired precision and are computed dynamically: https://github.com/JuliaLang/julia/blob/58ffe7e3ed3a93a9d816097548e785284f57fbd4/base/irrationals.jl#L182-L186

**Comment by hyrodium** [comment]
This issue can be closed with this comment: https://github.com/JuliaMath/IrrationalConstants.jl/issues/1#issuecomment-859612919
